"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,Check,ChevronRight,Clock3,Home,ImagePlus,ListChecks,Pause,Play,Sparkles,Trophy,X} from "lucide-react";
type Mode="quick"|"normal"|"deep"; type Screen="home"|"setup"|"analyzing"|"plan"|"cleaning"|"done";
const raw={quick:[["Recolha o lixo","Pegue embalagens, papéis e itens descartáveis.",2,"🗑️"],["Junte as roupas","Sujas no cesto; limpas sobre a cama.",3,"👕"],["Libere as superfícies","Agrupe os objetos em seus lugares.",2,"✨"]],normal:[["Retire copos e pratos","Leve toda a louça para a cozinha.",2,"🥛"],["Recolha o lixo","Percorra o cômodo com uma sacola.",3,"🗑️"],["Separe as roupas","Sujas no cesto; limpas nos cabides.",5,"👕"],["Arrume a cama","Estique o lençol e organize os travesseiros.",4,"🛏️"],["Organize a mesa","Deixe só o que você usa todos os dias.",5,"🧺"],["Faça o reset final","Guarde itens soltos e libere o caminho.",3,"✨"]],deep:[["Esvazie o que não pertence aqui","Retire louça, lixo e objetos de outros cômodos.",7,"📦"],["Separe todas as roupas","Crie grupos: lavar, guardar e doar.",10,"👕"],["Renove a cama","Troque a roupa de cama.",8,"🛏️"],["Organize por categoria","Agrupe livros, eletrônicos e papéis.",12,"🧺"],["Limpe as superfícies","Tire o pó de cima para baixo.",8,"🧽"],["Finalize o chão","Aspire ou varra do fundo para a saída.",10,"🧹"]]} as const;
const labels={quick:["Reset rápido","5–8 min"],normal:["Organização completa","15–25 min"],deep:["Limpeza profunda","45–60 min"]};
export default function Page(){
 const[screen,setScreen]=useState<Screen>("home"),[mode,setMode]=useState<Mode>("normal"),[photo,setPhoto]=useState<string>(),[after,setAfter]=useState<string>(),[task,setTask]=useState(0),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false);const file=useRef<HTMLInputElement>(null),afterFile=useRef<HTMLInputElement>(null),tasks=raw[mode];
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[running]);
 const fmt=(n:number)=>`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
 const read=(f:File|undefined,set:(v:string)=>void)=>{if(!f)return;const r=new FileReader;r.onload=()=>set(String(r.result));r.readAsDataURL(f)};
 const reset=()=>{setScreen("home");setPhoto(undefined);setAfter(undefined);setTask(0);setSeconds(0);setRunning(false)};
 const next=()=>task===tasks.length-1?(setRunning(false),setScreen("done")):setTask(task+1);
 return <main className="shell"><section className="phone"><header><button className="brand" onClick={reset}><i><Sparkles/></i>TidyNext</button><button className="avatar">RM</button></header>
 {screen==="home"&&<div className="page home"><p className="kicker">BOA NOITE, RAMON</p><h1>Qual bagunça vamos<br/>resolver agora?</h1><button className="scan" onClick={()=>setScreen("setup")}><i><Camera/></i><span><b>Escanear uma bagunça</b><small>A IA cria o seu plano em segundos</small></span><ChevronRight/></button><button className="panic" onClick={()=>{setMode("quick");setScreen("setup")}}><i>😩</i><span><b>Não sei por onde começar</b><small>Mostre o ambiente. Pense só no próximo passo.</small></span></button><div className="section"><h2>Esta semana</h2><button>Ver histórico</button></div><div className="stats"><article>🔥<b>4</b><small>dias seguidos</small></article><article><Clock3/><b>54 min</b><small>organizando</small></article><article>✦<b>3</b><small>resets feitos</small></article></div><div className="room"><i>🛏️</i><span><small>SEU QUARTO</small><b>Está na hora de um reset?</b><em>Última organização há 5 dias</em></span><strong>86<small>SCORE</small></strong></div></div>}
 {screen==="setup"&&<div className="page setup"><button className="close" onClick={()=>setScreen("home")}><X/></button><div className="center"><span className="kicker">NOVO RESET</span><h1>Mostre a bagunça.<br/>Nós cuidamos do plano.</h1><p>Uma foto ampla e bem iluminada funciona melhor.</p></div><input ref={file} hidden type="file" accept="image/*" capture="environment" onChange={e=>read(e.target.files?.[0],setPhoto)}/><button className={"photo "+(photo?"ready":"")} onClick={()=>file.current?.click()} style={photo?{backgroundImage:`linear-gradient(transparent,#071b1999),url(${photo})`}:undefined}>{photo?<><b><Check/> Foto pronta</b><small>Toque para trocar</small></>:<><i><ImagePlus/></i><b>Tirar ou escolher foto</b><small>JPG, PNG ou HEIC</small></>}</button><div className="modeTitle"><b>Quanto tempo você tem?</b><small>Você pode mudar depois</small></div><div className="modes">{(["quick","normal","deep"] as Mode[]).map(k=><button key={k} className={mode===k?"active":""} onClick={()=>setMode(k)}><i>{k==="quick"?"⚡":k==="normal"?"✨":"🫧"}</i><b>{k==="quick"?"Rápido":k==="normal"?"Normal":"Profundo"}</b><small>{labels[k][1]}</small></button>)}</div><button className="primary" disabled={!photo} onClick={()=>{setScreen("analyzing");setTimeout(()=>setScreen("plan"),2100)}}><Sparkles/>Criar meu plano</button><p className="privacy">🔒 Sua foto é usada apenas para criar este plano.</p></div>}
 {screen==="analyzing"&&<div className="page analyzing"><div className="radar"><i/><Sparkles/></div><span className="kicker">ANALISANDO O AMBIENTE</span><h1>Transformando bagunça<br/>em passos simples…</h1><div className="dots">● ● ●</div><p>Identificando roupas, superfícies e itens fora do lugar</p></div>}
 {screen==="plan"&&<div className="page plan"><button className="close" onClick={()=>setScreen("setup")}><X/></button><span className="pill"><Sparkles/> PLANO PRONTO</span><h1>Você consegue resolver isso em cerca de <em>{mode==="quick"?"7":mode==="normal"?"22":"55"} minutos.</em></h1><div className="insight">💡 <p><b>O maior impacto visual</b> virá de recolher as roupas e liberar a cama primeiro.</p></div><div className="summary"><div><ListChecks/><span><b>{tasks.length} passos</b><small>{labels[mode][0]}</small></span></div><div><Clock3/><span><b>{labels[mode][1]}</b><small>tempo estimado</small></span></div></div><div className="preview">{tasks.slice(0,4).map((t,i)=><div key={t[0]}><i>{i+1}</i><b>{t[0]}</b><small>{t[2]} min</small></div>)}</div><button className="primary" onClick={()=>{setScreen("cleaning");setRunning(true)}}><Play/>Começar agora</button></div>}
 {screen==="cleaning"&&<div className="page cleaning"><div className="cleanTop"><button onClick={()=>setScreen("plan")}><X/></button><b>RESET EM ANDAMENTO</b><button onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{fmt(seconds)}</button></div><div className="progress"><i style={{width:`${task/tasks.length*100}%`}}/></div><p className="kicker">PASSO {task+1} DE {tasks.length}</p><div className="taskIcon">{tasks[task][3]}</div><h1>{tasks[task][0]}</h1><p>{tasks[task][1]}</p><span className="estimate"><Clock3/> Aproximadamente <b>{tasks[task][2]} minutos</b></span><button className="complete" onClick={next}><Check/>Concluído</button><button className="skip" onClick={next}>Pular por agora</button><small className="encourage">Não pense no quarto inteiro. Faça somente isso agora.</small></div>}
 {screen==="done"&&<div className="page done"><div className="trophy"><Trophy/></div><span className="kicker">RESET CONCLUÍDO</span><h1>Olha o que você<br/>acabou de fazer.</h1><p>{tasks.length} passos concluídos em {fmt(seconds)}.</p><div className="photos"><div style={photo?{backgroundImage:`url(${photo})`}:undefined}><b>ANTES</b></div><input ref={afterFile} hidden type="file" accept="image/*" capture="environment" onChange={e=>read(e.target.files?.[0],setAfter)}/><button onClick={()=>afterFile.current?.click()} style={after?{backgroundImage:`url(${after})`}:undefined}>{after?<b>DEPOIS</b>:<><Camera/><span>Adicionar foto<br/>do resultado</span></>}</button></div><div className="score"><span><small>ROOM SCORE</small><b>42 → 91</b></span><strong>+49</strong></div><button className="primary" onClick={reset}><Home/>Voltar ao início</button></div>}
 {screen==="home"&&<nav><button className="on"><Home/>Início</button><button>▦<span>Cômodos</span></button><button className="camera" onClick={()=>setScreen("setup")}><Camera/></button><button><ListChecks/>Histórico</button><button>○<span>Perfil</span></button></nav>}
 </section></main>}
